# Generated by Django 3.2.5 on 2022-01-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Alex', max_length=50)),
                ('lastname', models.CharField(default='Peters', max_length=50)),
                ('age', models.IntegerField(default=45)),
                ('state', models.CharField(default='Enugu', max_length=50)),
                ('area', models.CharField(default='behind flat', max_length=50)),
                ('email', models.EmailField(default='Alexie@email.com', max_length=254)),
                ('gender', models.CharField(default='female', max_length=50)),
                ('agegroup', models.CharField(default='18-25', max_length=50)),
                ('religion', models.CharField(default='christian', max_length=50)),
                ('discipline', models.CharField(default='science', max_length=50)),
                ('gender1', models.CharField(default='female1', max_length=50)),
                ('smoking', models.CharField(default='no', max_length=50)),
                ('alcohol', models.CharField(default='no', max_length=50)),
                ('uncleanliness', models.CharField(default='no', max_length=50)),
                ('lateness', models.CharField(default='no', max_length=50)),
                ('homepartying', models.CharField(default='no', max_length=50)),
                ('alias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
